// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wvs

import (
	"github.com/elct9620/wvs/app"
	"github.com/elct9620/wvs/app/web"
)

// Injectors from wire.go:

func InitializeTest() (*app.Application, error) {
	scene := web.NewScene()
	webWeb := web.New(scene)
	application := app.New(webWeb)
	return application, nil
}
