// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/elct9620/wvs/app"
	"github.com/elct9620/wvs/app/api"
	"github.com/elct9620/wvs/app/web"
	"github.com/elct9620/wvs/app/ws"
)

// Injectors from wire.go:

func Initialize() (*app.Application, error) {
	scene := web.NewScene()
	webWeb := web.New(scene)
	apiApi := api.New()
	webSocket := ws.New()
	application := app.New(webWeb, apiApi, webSocket)
	return application, nil
}
